# configuration for build badge
language: scala

# configurations for codecov badge
scala:
  - 2.12.8

script:
  - sbt clean coverage test coverageReport

env:
  - CODECOV_TOKEN=ec808af4-9698-45c4-a5a4-290d22820ea9

after_success:
  - bash <(curl -s https://codecov.io/bash)