version: 2.1
jobs:
  build:
    working_directory: ~/json
    docker:
      - image: openjdk:8
    environment:
      SBT_VERSION: 1.3.3
      TZ: Asia/Tokyo
      JVM_OPTS: -Xms2G -Xmx2G -Xss2M -XX:ReservedCodeCacheSize=256m
    steps:
      - run:
          name: Get sbt binary
          command: |
            apt update && apt install -y curl
            curl -L -o sbt-$SBT_VERSION.deb https://dl.bintray.com/sbt/debian/sbt-$SBT_VERSION.deb
            dpkg -i sbt-$SBT_VERSION.deb
            rm sbt-$SBT_VERSION.deb
            apt-get update
            apt-get install -y sbt
            apt-get clean && apt-get autoclean
      - checkout
      - restore_cache:
          # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
          key: sbt-cache
      - run:
          name: clean
          command: cat /dev/null | sbt clean
      - run:
          name: compile
          command: cat /dev/null | sbt test:compile
      - save_cache:
          key: sbt-cache
          paths:
            - "~/.ivy2/cache"
            - "~/.sbt"
            - "~/.m2"
      - run:
          name: coverage
          command: cat /dev/null | sbt coverage
      - run:
          name: test AvatarValidationSpec
          command: cat /dev/null | sbt "testOnly validation.village.AvatarValidationSpec"
      - run:
          name: test BaseValidationSpec
          command: cat /dev/null | sbt "testOnly validation.village.BaseValidationSpec"
      - run:
          name: test CharacterValidationSpec
          command: cat /dev/null | sbt "testOnly validation.village.CharacterValidationSpec"
      - run:
          name: test RoleValidationSpec
          command: cat /dev/null | sbt "testOnly validation.village.RoleValidationSpec"
      - run:
          name: test LobbyUnitTestSpec
          command: cat /dev/null | sbt "testOnly engine.lobby.LobbyUnitTestSpec"
      - run:
          name: test LobbyProcessingEngineSpec
          command: cat /dev/null | sbt "testOnly engine.lobby.LobbyProcessingEngineSpec"
      - run:
          name: test VillageUnitTestSpec
          command: cat /dev/null | sbt "testOnly engine.village.VillageUnitTestSpec"
      - run:
          name: test VillageProcessingEngineSpec
          command: cat /dev/null | sbt "testOnly engine.village.VillageProcessingEngineSpec"
      - run:
          name: coverage report
          command: cat /dev/null | sbt coverageReport